-- ExternalTools: herramientas externas que descarga el instalador (HIMALAYA…).
-- La tabla ya existe en Supabase creada a mano (id int8 PK, created_at
-- timestamptz, nombre varchar, enlace text); IF NOT EXISTS para que la
-- migración converja sin tocarla en los entornos donde ya está.
CREATE TABLE IF NOT EXISTS "ExternalTools" (
  "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "nombre"     VARCHAR NOT NULL,
  "enlace"     TEXT NOT NULL,
  CONSTRAINT "ExternalTools_pkey" PRIMARY KEY ("id")
);
